server:
  port: 8080
  
spring:
  application:
    name: loja

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:8761/eureka